# Generated by Django 3.2.12 on 2022-04-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Класс')),
                ('class_letter', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж')], max_length=1, verbose_name='Параллель')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('МБОУ', 'МБОУ'), ('Гимназия', 'Гимназия'), ('Лицей', 'Лицей'), ('Интернат', 'Интернат')], default='', max_length=10, verbose_name='Тип школы')),
                ('school_name', models.CharField(default='', max_length=32, verbose_name='Название школы')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('website', models.URLField(unique=True, verbose_name='Сайт школы')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=32, unique=True, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Д/З', 'Домашняя работа'), ('К/Р', 'Контрольная работа'), ('С/Р', 'Самостоятельная работа')], max_length=32, verbose_name='Тип работы')),
                ('plan_text', models.CharField(max_length=128, verbose_name='Текст')),
                ('date', models.DateField(verbose_name='Дата')),
                ('edu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=32, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=32, verbose_name='Отчество')),
                ('phone', models.CharField(default='', max_length=11, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Эл. почта')),
                ('photo', models.ImageField(blank=True, default='photos/default_photo.jpg', upload_to='photos/', verbose_name='Фото')),
                ('classes', models.ManyToManyField(to='main.Class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school', verbose_name='Школа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=32, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=32, verbose_name='Отчество')),
                ('phone', models.CharField(default='', max_length=11, unique=True, validators=[main.utils.phone_validator], verbose_name='Номер телефона')),
                ('email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Эл. почта')),
                ('photo', models.ImageField(blank=True, default='photos/default_photo.jpg', upload_to='photos/', verbose_name='Фото')),
                ('edu_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class', verbose_name='Класс')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school', verbose_name='Школа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('П', 'П'), ('Б', 'Б')], max_length=1, verbose_name='Оценка')),
                ('mark_type', models.CharField(choices=[('Классная работа', 'Классная работа'), ('Домашняя работа', 'Домашняя работа'), ('Самостоятельная работа', 'Самостоятельная работа'), ('Контрольная работа', 'Контрольная работа'), ('Итоговая оценка', 'Итоговая оценка')], default='Классная работа', max_length=32, verbose_name='Тип работы')),
                ('comment', models.CharField(blank=True, default='Отсутствует', max_length=100, verbose_name='Комментарий')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выставления')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentprofile', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
        ),
    ]
