# Generated by Django 3.2.12 on 2022-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_letter',
            new_name='letter',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='class_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='class',
            name='lessons',
            field=models.ManyToManyField(to='main.Subject', verbose_name='Предметы'),
        ),
    ]
