# Generated by Django 3.2.12 on 2022-04-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220411_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='lessons',
            new_name='subjects',
        ),
        migrations.DeleteModel(
            name='WorkingPlan',
        ),
    ]
