# Generated by Django 3.2.12 on 2022-04-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220412_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='class_subjects', to='main.Subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='classes',
            field=models.ManyToManyField(related_name='teacher_classes', to='main.Class', verbose_name='Классы'),
        ),
    ]
