# Generated by Django 3.2.12 on 2022-04-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_subject_name_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='mark_type',
        ),
    ]
