# Generated by Django 3.2.12 on 2022-04-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_mark_mark_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('ДЗ', 'Домашняя работа'), ('КР', 'Контрольная работа'), ('СР', 'Самостоятельная работа'), ('ОТВ', 'Работа на уроке')], max_length=32, verbose_name='Тип работы')),
                ('plan_text', models.CharField(max_length=128, verbose_name='Текст')),
                ('date', models.DateField(verbose_name='Дата')),
                ('edu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет')),
            ],
        ),
    ]
