# Generated by Django 3.2.12 on 2022-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_workingplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Класс'),
        ),
    ]
