# Generated by Django 3.2.12 on 2022-04-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='working_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.workingplan', verbose_name='План работы'),
        ),
    ]
