# Generated by Django 3.2.12 on 2022-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220428_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='work_type',
            field=models.CharField(choices=[('ДЗ', 'Домашняя работа'), ('КР', 'Контрольная работа'), ('СР', 'Самостоятельная работа'), ('ОТВ', 'Работа на уроке')], max_length=32, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='workingplan',
            name='plan_type',
            field=models.CharField(choices=[('ДЗ', 'Домашняя работа'), ('КР', 'Контрольная работа'), ('СР', 'Самостоятельная работа'), ('ОТВ', 'Работа на уроке')], max_length=32, verbose_name='Тип работы'),
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
