# Generated by Django 3.2.12 on 2022-04-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220428_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='work_type',
        ),
    ]
