# Generated by Django 3.2.12 on 2022-04-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mark_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingplan',
            name='plan_text',
            field=models.CharField(blank=True, max_length=128, verbose_name='Текст'),
        ),
    ]
