# Generated by Django 3.2.12 on 2022-04-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_workingplan_plan_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingplan',
            old_name='plan_type',
            new_name='work_type',
        ),
    ]
