# Generated by Django 3.2.12 on 2022-04-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_plan_type_workingplan_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='work_type',
            field=models.CharField(choices=[('ДЗ', 'Домашняя работа'), ('КР', 'Контрольная работа'), ('СР', 'Самостоятельная работа'), ('ОТВ', 'Работа на уроке')], default='ОТВ', max_length=32, verbose_name='Тип работы'),
        ),
    ]
