# Generated by Django 3.2.12 on 2022-05-01 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_mark_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 1), verbose_name='Дата выставления'),
        ),
    ]
