# Generated by Django 3.2.12 on 2022-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_mark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(verbose_name='Дата выставления'),
        ),
    ]
